2024-06-01 01:57:37,589: asyncio: INFO: [MLTrader] Executing the initialize lifecycle method
2024-06-01 01:57:37,785: alpaca.trading.stream: INFO: connected to: BaseURL.TRADING_STREAM_PAPER
2024-06-01 01:57:38,292: root: INFO: Current backtesting datetime 2023-05-30 08:30:00-04:00
2024-06-01 01:57:38,293: asyncio: INFO: [MLTrader] Executing the before_market_opens lifecycle method
2024-06-01 01:57:38,294: root: INFO: Current backtesting datetime 2023-05-30 09:30:00-04:00
2024-06-01 01:57:38,294: asyncio: INFO: [MLTrader] Executing the before_starting_trading lifecycle method
2024-06-01 01:57:38,295: asyncio: INFO: [MLTrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-06-01 01:57:38[0m
2024-06-01 01:57:38,296: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-06-01 01:57:38,778: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-06-01 01:57:38,779: asyncio: INFO: [MLTrader] [34mTrading iteration ended at 2024-06-01 01:57:38[0m
2024-06-01 01:57:38,780: asyncio: INFO: [MLTrader] [34mSleeping for 1800 seconds[0m
2024-06-01 01:57:38,780: root: INFO: Current backtesting datetime 2023-05-30 10:00:00-04:00
2024-06-01 01:57:38,781: asyncio: INFO: [MLTrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-06-01 01:57:38[0m
2024-06-01 01:57:38,781: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-06-01 01:57:38,782: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-06-01 01:57:38,782: asyncio: ERROR: [MLTrader] dtype '<class 'datetime.datetime'>' not understood
2024-06-01 01:57:38,817: asyncio: ERROR: [MLTrader] Traceback (most recent call last):
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\strategies\strategy_executor.py", line 923, in run
    self._run_trading_session()
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\strategies\strategy_executor.py", line 871, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\strategies\strategy_executor.py", line 262, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\strategies\strategy_executor.py", line 286, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\strategies\strategy_executor.py", line 397, in _on_trading_iteration
    raise e
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\strategies\strategy_executor.py", line 369, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\trygv\OneDrive\Dokumenter\IT1\algorithmic-trading-python\finance.py", line 624, in on_trading_iteration
    self.runnit(cash, last_price, quantity)
  File "c:\Users\trygv\OneDrive\Dokumenter\IT1\algorithmic-trading-python\finance.py", line 584, in runnit
    sentiment = self.get_sentiment()
                ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\trygv\OneDrive\Dokumenter\IT1\algorithmic-trading-python\finance.py", line 570, in get_sentiment
    today_row = df[df['Date'].astype(datetime).strftime('%Y-%m-%d %H:%M:%S') == today.strftime('%Y-%m-%d %H:%M:%S')]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\managers.py", line 430, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\dtypes\astype.py", line 231, in astype_array_safe
    dtype = pandas_dtype(dtype)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trygv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\dtypes\common.py", line 1666, in pandas_dtype
    raise TypeError(f"dtype '{dtype}' not understood")
TypeError: dtype '<class 'datetime.datetime'>' not understood

2024-06-01 01:57:38,821: asyncio: INFO: [MLTrader] Executing the on_bot_crash event method
2024-06-01 01:57:39,336: root: INFO: Backtesting finished
2024-06-01 01:57:39,594: root: INFO: There were no trades in this backtest.
2024-06-01 01:57:39,759: root: ERROR: Not enough data to create a tearsheet, at least 2 days of data are required. Skipping
2024-06-01 01:57:39,759: backtest_stats: INFO: Backtest took 0:00:02.171572 for a speed of 0.000
